version: '3'
services:

  db:
    profiles: ["backend"]
    image: neo4j:latest
    restart: always
    ports:
      - "7687:7687"
      - "7474:7474"
    environment:
      - NEO4J_AUTH=${NEO4J_AUTH}
      - NEO4J_DBMS_MEMORY_PAGECACHE_SIZE=${NEO4J_DBMS_MEMORY_PAGECACHE_SIZE}
      - NEO4J_DBMS_MEMORY_HEAP_MAX_SIZE=${NEO4J_DBMS_MEMORY_HEAP_MAX_SIZE}
    volumes:
      - ${NEO4J_DATA_DIR}:/data
      - ${NEO4J_LOGS_DIR}:/logs
      - ${NEO4J_IMPORT_DIR}:/var/lib/neo4j/import
      - ${NEO4J_PLUGIN_DIR}:/plugins

  cache:
    profiles: ["backend", "cache"]
    image: redis
    ports:
      - "6379:6379"

  sfu:
    profiles: ["webrtc", "backend"]
    image: livekit/livekit-server
    ports:
      - "7880:7880" 
      - "7881:7881" 
      - "7882:7882/udp"
    command: 
       --config '/livekit.yaml'
    volumes:
      - ${LKCONFIG_PATH}:/livekit.yaml

  # recorder:
  #   profile: ["webrtc", "backend"]
  #   image: livekit/egress
  #   ports: 
  #     -

  # ai:
  #   image: openvino/model_server
  #   ports: 
                                                                                                                                     

