version: '3'
services:

  db:
    # TODO: Add Kafka pub/sub to perform operations after receieving data from stream.
    profiles: ["backend", "db"]
    image: neo4j:latest
    restart: unless-stopped
    ports:
      - "7687:7687"
      - "7474:7474"
        # - "7473:7473" # For Https
    environment:
      - NEO4J_AUTH=${NEO4J_AUTH}
      - NEO4J_DBMS_MEMORY_PAGECACHE_SIZE=${NEO4J_DBMS_MEMORY_PAGECACHE_SIZE}
      - NEO4J_DBMS_MEMORY_HEAP_MAX_SIZE=${NEO4J_DBMS_MEMORY_HEAP_MAX_SIZE}
    volumes:
      - ${NEO4J_DATA_DIR}:/data
      - ${NEO4J_LOGS_DIR}:/logs
      - ${NEO4J_IMPORT_DIR}:/var/lib/neo4j/import
      - ${NEO4J_PLUGIN_DIR}:/plugins
        # - ${NEO4J_CONF_DIR}:/conf

  cache:
    profiles: ["backend", "cache"]
    image: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command:
      redis-server /usr/local/etc/redis 
    volumes:
      - ${REDIS_CONF}:/usr/local/etc/redis
      - ${REDIS_ACL}:/etc/redis/users.acl

  sfu:
    # TODO: Add prometheus to monitor service
    profiles: ["webrtc", "backend"]
    image: livekit/livekit-server
    restart: unless-stopped
    ports:
      - "7880:7880" 
      - "7881:7881" 
      - "7882:7882/udp"
    command: 
       --config '/livekit.yaml'
    volumes:
      - ${LKCONFIG_PATH}:/livekit.yaml
    depends_on: # This will deprecate in near future.
      - cache

  # recorder:
  #   profile: ["webrtc", "backend"]
  #   image: livekit/egress
  #   ports: 
  #     -

  ai:
    profiles: ["ai","backend"]
    image: openvino/model_server
    ports: 
     - "9001:9001"
     - "8001:8001"
    volumes:
     - ${MODELS_PATH}:/models/
     - ${MODEL_SERVER_CONFIG}:/opt/ml/config.json
    command:
      --config_path /opt/ml/config.json --port 9001 --rest_port 8001

